version: "3.9"
services:
  selenium:
    build: .
    image: selenium_dropbox:latest
#    ports:
#      - "7900:7900"
    volumes:
      - .:/app/
      - /etc/localtime:/etc/localtime:ro
    shm_size: '2gb'